# Change these first
owner: greyhoundforty # Your GitHub organization or username, where this repository lives
repo: gh40-uptime # The name of this repository

sites:
  - name: Ryan Tiffany
    url: https://ryantiffany.com
  - name: Gh40
    url: https://gh40.net
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Kagi
    url: https://kagi.com
  - name: GitHub
    url: https://github.com
  - name: Google DNS 
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Cloudflare DNS
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /gh40-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: gh40-uptime
  introTitle: "Uptime monitor and status page, powered by GitHub."
  introMessage: "🚀 **[Learn more here &rarr;](https://upptime.js.org)**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
